welcome: "Welcome to What's Up Raleigh! A quick and easy way to keep track of the countless happenings in Raleigh: from concerts to festivals, trivia nights to karaoke spots, plus a comprehensive listing of the daily food and drink specials!  Updated frequently, so come back often and check out What's Up in Raleigh!"

twitter_url: "https://twitter.com/[add yours]""
facebook_url: "https://facebook.com/[add yours]"
